version: "3.5"

services:
  app:
    build: $PWD/.
    restart: unless-stopped
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/src:/app
    ports:
      - 8080:8080
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080

volumes:
  build:
